CREATE TABLE `signup_intakes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(128) NOT NULL,
	`companyName` varchar(256) NOT NULL,
	`dba` varchar(256),
	`ein` varchar(32) NOT NULL,
	`businessType` varchar(128),
	`businessEntity` enum('LLC','Inc','PrivateCorp','Partnership','SoleProprietor') NOT NULL,
	`ownerFirstName` varchar(128) NOT NULL,
	`ownerLastName` varchar(128) NOT NULL,
	`ownerPhone` varchar(32) NOT NULL,
	`ownerPhoneExt` varchar(16),
	`ownerEmail` varchar(320) NOT NULL,
	`hasMainContact` boolean DEFAULT false,
	`contactName` varchar(128),
	`contactEmail` varchar(320),
	`contactPhone` varchar(32),
	`contactPhoneExt` varchar(16),
	`contactMobile` varchar(32),
	`businessStreet` varchar(256) NOT NULL,
	`businessStreet2` varchar(256),
	`businessCity` varchar(128) NOT NULL,
	`businessState` varchar(64) NOT NULL,
	`businessZip` varchar(16) NOT NULL,
	`businessCountry` varchar(128) DEFAULT 'United States',
	`sameAsBusiness` boolean DEFAULT true,
	`billingStreet` varchar(256),
	`billingStreet2` varchar(256),
	`billingCity` varchar(128),
	`billingState` varchar(64),
	`billingZip` varchar(16),
	`billingCountry` varchar(128),
	`billingAttention` varchar(128),
	`adminUsers` text NOT NULL,
	`authorizedSignerName` varchar(128) NOT NULL,
	`authorizedSignerTitle` varchar(128) NOT NULL,
	`signatureDate` date,
	`signatureConfirmed` boolean DEFAULT false,
	`goHighLevelContactId` varchar(128),
	`goHighLevelOpportunityId` varchar(128),
	`agreementStatus` varchar(64) DEFAULT 'Pending',
	`status` varchar(64) DEFAULT 'Completed',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `signup_intakes_id` PRIMARY KEY(`id`),
	CONSTRAINT `signup_intakes_sessionId_unique` UNIQUE(`sessionId`)
);
