export const authorizationCopy = {
  en: {
    eyebrow: 'SaffHire for Driver Pipeline',
    title: 'Background check and MVR authorization',
    intro: 'Complete this form so Driver Pipeline can request a criminal background screening and motor vehicle report through SaffHire. Your signature and the submission time are stored with the form.',
    received: 'Authorization received',
    thanks: 'Thank you. Your form is signed and stored.',
    reference: 'Reference number',
    signedAt: 'Signed at',
    keep: 'Keep this reference number. Driver Pipeline and SaffHire can retrieve the signed authorization with it.',
    disclosureTitle: '1. Standalone disclosure',
    disclosure: 'Driver Pipeline may obtain a consumer report about you from SaffHire, a consumer reporting agency, for employment purposes. The report may include a criminal background screening and a motor vehicle report. This disclosure is provided on its own, before you authorize the report.',
    disclosureCheck: 'I have received and read this standalone disclosure that a consumer report may be obtained for employment purposes.',
    rightsTitle: '2. Summary of Your Rights',
    rights: 'Federal law requires that you receive A Summary of Your Rights Under the Fair Credit Reporting Act before a background check is ordered. Acknowledge that you have received it below.',
    rightsCheck: 'I acknowledge receipt of A Summary of Your Rights Under the Fair Credit Reporting Act and certify that I have read and understand my rights.',
    authTitle: '3. Authorization',
    paragraphs: [
      'In connection with my application for employment, continued employment, or other permissible purpose, I understand that Driver Pipeline may obtain my motor vehicle record (MVR) and conduct a criminal background screening through its designated agents or consumer reporting agencies, including Saffhire, from state Departments of Motor Vehicles (DMV), law enforcement agencies, courts, or other authorized sources.',
      'The MVR may include my driving history, license status, traffic violations, accidents, and related information. The criminal background screening may include my criminal history, such as arrests, convictions, and other records from federal, state, or local agencies or courts.',
      'I agree that this information will be used for employment-related purposes, including evaluating my eligibility to operate a company or personal vehicle for company business and for employment, retention, promotion, or reassignment with Driver Pipeline.',
      'I authorize Driver Pipeline, Saffhire, and their agents to obtain and review my MVR and criminal background information now and, if employed, during my employment for retention, promotion, or reassignment, as permitted by law. I authorize any law enforcement agency, state or federal agency, institution, school, university, information service bureau, employer, or insurance company to provide requested background information to Driver Pipeline or Saffhire.',
      'This authorization remains in effect during my employment unless revoked in writing.',
    ],
    firstName: 'First name (required)',
    lastName: 'Last name (required)',
    middleName: 'Middle name (required)',
    noMiddle: 'Click here if you do not have a legal middle name.',
    dob: 'Date of birth (required)',
    ssn: 'Social Security number (required)',
    email: 'Email address (required)',
    phone: 'Phone (required)',
    dl: 'DL number (required)',
    expiration: 'License expiration date (required)',
    issued: 'Date issued (required)',
    state: 'Issuing state (required)',
    select: 'Select',
    address: 'Current address (required)',
    moved: 'Approximate date moved in',
    otherNames: 'Other names used, including maiden name',
    years: 'Years known by other names',
    signTitle: '4. Electronic signature',
    signHelp: 'Draw your signature, then type your full legal name. The server time stamp, IP address, and reference number are stored with the form.',
    clear: 'Clear signature',
    typed: 'Type your full legal name',
    esign: 'I agree to sign this authorization electronically. My drawn signature and typed name are my legal signature.',
    submit: 'Sign and submit',
    submitting: 'Submitting...',
    stateNote: 'Pennsylvania, New Hampshire, and Washington may require a separate state MVR form before a driving record can be ordered. This page does not replace those state forms.',
    submitError: 'Unable to submit the authorization.',
    timeZoneLabel: 'Central Time',
  },
  es: {
    eyebrow: 'SaffHire para Driver Pipeline',
    title: 'Autorizacion de verificacion de antecedentes y reporte de manejo',
    intro: 'Complete este formulario para que Driver Pipeline pueda solicitar una verificacion de antecedentes penales y un reporte de vehiculo de motor por medio de SaffHire. Su firma y la hora de envio quedan guardadas con el formulario.',
    received: 'Autorizacion recibida',
    thanks: 'Gracias. Su formulario esta firmado y guardado.',
    reference: 'Numero de referencia',
    signedAt: 'Firmado el',
    keep: 'Guarde este numero de referencia. Driver Pipeline y SaffHire pueden recuperar la autorizacion firmada con el.',
    disclosureTitle: '1. Divulgacion independiente',
    disclosure: 'Driver Pipeline puede obtener un informe del consumidor sobre usted de SaffHire, una agencia de informes del consumidor, para fines de empleo. El informe puede incluir una verificacion de antecedentes penales y un reporte de vehiculo de motor. Esta divulgacion se entrega por separado, antes de que usted autorice el informe.',
    disclosureCheck: 'He recibido y leido esta divulgacion independiente de que se puede obtener un informe del consumidor para fines de empleo.',
    rightsTitle: '2. Resumen de sus derechos',
    rights: 'La ley federal exige que usted reciba un Resumen de sus derechos bajo la Ley de Informes de Credito Justos antes de que se ordene una verificacion de antecedentes. Confirme abajo que lo ha recibido.',
    rightsCheck: 'Confirmo que recibi un Resumen de sus derechos bajo la Ley de Informes de Credito Justos y certifico que he leido y entiendo mis derechos.',
    authTitle: '3. Autorizacion',
    paragraphs: [
      'En relacion con mi solicitud de empleo, empleo continuo u otro proposito permitido, entiendo que Driver Pipeline puede obtener mi reporte de vehiculo de motor (MVR) y realizar una verificacion de antecedentes penales por medio de sus agentes designados o agencias de informes del consumidor, incluyendo Saffhire, de los Departamentos de Vehiculos de Motor estatales (DMV), agencias del orden publico, tribunales u otras fuentes autorizadas.',
      'El MVR puede incluir mi historial de manejo, el estado de la licencia, infracciones de transito, accidentes e informacion relacionada. La verificacion de antecedentes penales puede incluir mi historial penal, como arrestos, condenas y otros registros de agencias o tribunales federales, estatales o locales.',
      'Acepto que esta informacion se usara para fines relacionados con el empleo, incluyendo evaluar mi elegibilidad para operar un vehiculo de la empresa o un vehiculo personal para negocios de la empresa, y para empleo, retencion, promocion o reasignacion con Driver Pipeline.',
      'Autorizo a Driver Pipeline, Saffhire y sus agentes a obtener y revisar mi MVR y mi informacion de antecedentes penales ahora y, si soy empleado, durante mi empleo para retencion, promocion o reasignacion, segun lo permita la ley. Autorizo a cualquier agencia del orden publico, agencia estatal o federal, institucion, escuela, universidad, oficina de servicios de informacion, empleador o compania de seguros a proporcionar la informacion de antecedentes solicitada a Driver Pipeline o Saffhire.',
      'Esta autorizacion permanece vigente durante mi empleo, a menos que la revoque por escrito.',
    ],
    firstName: 'Nombre (obligatorio)',
    lastName: 'Apellido (obligatorio)',
    middleName: 'Segundo nombre (obligatorio)',
    noMiddle: 'Haga clic aqui si no tiene un segundo nombre legal.',
    dob: 'Fecha de nacimiento (obligatorio)',
    ssn: 'Numero de Seguro Social (obligatorio)',
    email: 'Correo electronico (obligatorio)',
    phone: 'Telefono (obligatorio)',
    dl: 'Numero de licencia (obligatorio)',
    expiration: 'Fecha de vencimiento de la licencia (obligatorio)',
    issued: 'Fecha de emision (obligatorio)',
    state: 'Estado que emitio la licencia (obligatorio)',
    select: 'Seleccione',
    address: 'Direccion actual (obligatorio)',
    moved: 'Fecha aproximada en que se mudo',
    otherNames: 'Otros nombres usados, incluyendo el apellido de soltera',
    years: 'Anos conocido por otros nombres',
    signTitle: '4. Firma electronica',
    signHelp: 'Dibuje su firma y luego escriba su nombre legal completo. La hora del servidor, la direccion IP y el numero de referencia quedan guardados con el formulario.',
    clear: 'Borrar firma',
    typed: 'Escriba su nombre legal completo',
    esign: 'Acepto firmar esta autorizacion de forma electronica. Mi firma dibujada y mi nombre escrito son mi firma legal.',
    submit: 'Firmar y enviar',
    submitting: 'Enviando...',
    stateNote: 'Pensilvania, Nuevo Hampshire y Washington pueden exigir un formulario estatal aparte antes de solicitar un reporte de manejo. Esta pagina no reemplaza esos formularios estatales.',
    submitError: 'No se pudo enviar la autorizacion.',
    timeZoneLabel: 'hora del Centro',
  },
} as const;

export type AuthorizationLocale = keyof typeof authorizationCopy;
